### ISSUE TITLE
Computing mode for categorical variables

### ISSUE THREAD

**Issue by federicazoe** [mdogucu/stats67-su20-website#32]
A few students tripped into the "what statistics can we compute for a categorical variable" select-all question, including counts, proportions but also **mode**.

What is a good explanation for why we cannot compute the mode? In principle we could, right?

**Comment by mdogucu** [comment]
If the categorical variable can be expressed as a discrete random variable then yes since mode is found using pmf and pdf from a technical point. But having  categorical outcomes cannot make it a mode. For instance outcomes of a coin flip is H, T. However we could write a discrete random variable which would represent the number of heads in a single coin flip. In this case random variable can take values 0 or 1. This distribution would have two modes. Does this clarify?

**Comment by mdogucu** [comment]
From the lecture point of view, mode was presented along with mean and median for numerical variables. That is also worth noting.

**Comment by federicazoe** [comment]
I had understood it from the lecture point of view, but still I cannot understand it from the probabilistic point of view. To me it seems that any discrete distribution would be multimodal, if 0 or 1 is. From the [definition on wikipedia](https://en.wikipedia.org/wiki/Mode_(statistics)#:~:text=The%20mode%20of%20a%20set,most%20likely%20to%20be%20sampled.), it seems like "multimodal" is defined only for continuous variables.

**Comment by mdogucu** [comment]
I just went back to the question, so we did not specify a variable. Let's assume a nominal data and even in that case mode can be calculated. I will ask Catalina regrade for such responses.
